version: '2'
services:
  varnish:
      image: eeacms/varnish:4.1-6.3
      restart: always
      depends_on:
          - web
      ports:
          - "5000:6081"
          - "6085:6085"
      environment:
        VARNISH_MALLOC: "1g"
        BACKENDS_PORT: "3000"
        BACKENDS: "web"      
      links:
        - web
      volumes:
          - ./default.vcl:/etc/varnish/default.vcl:ro
  web:
    build: .
    command: npm run serve
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
